/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EventCard: typeof import('./components/events/EventCard.vue')['default']
    EventResults: typeof import('./components/EventResults.vue')['default']
    EventResultsFilters: typeof import('./components/EventResultsFilters.vue')['default']
    EventResultsHeader: typeof import('./components/EventResultsHeader.vue')['default']
    EventsFilter: typeof import('./components/events/EventsFilter.vue')['default']
    EventsList: typeof import('./components/events/EventsList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconTest: typeof import('./components/IconTest.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./components/SearchComponent.vue')['default']
  }
}
